# Generated by Django 5.2.12 on 2026-03-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('nasa_eonet', 'NASA EONET'), ('earthquake', 'USGS Earthquake'), ('weather', 'Weather API')], max_length=50)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('records_fetched', models.IntegerField(default=0)),
                ('records_new', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='EarthquakeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('depth', models.FloatField(help_text='Depth in km')),
                ('magnitude', models.FloatField()),
                ('magnitude_type', models.CharField(blank=True, max_length=10)),
                ('place', models.CharField(blank=True, max_length=500)),
                ('event_time', models.DateTimeField()),
                ('tsunami', models.BooleanField(default=False)),
                ('felt', models.IntegerField(blank=True, null=True)),
                ('significance', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('alert', models.CharField(blank=True, max_length=20, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-event_time'],
                'indexes': [models.Index(fields=['magnitude'], name='disasters_e_magnitu_b05df8_idx'), models.Index(fields=['latitude', 'longitude'], name='disasters_e_latitud_06ccad_idx'), models.Index(fields=['event_time'], name='disasters_e_event_t_a86aa7_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocationBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=300)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('avg_earthquake_magnitude', models.FloatField(default=0)),
                ('max_earthquake_magnitude', models.FloatField(default=0)),
                ('earthquake_frequency', models.FloatField(default=0, help_text='Average events per month')),
                ('avg_temperature', models.FloatField(blank=True, null=True)),
                ('avg_rainfall', models.FloatField(blank=True, null=True)),
                ('avg_wind_speed', models.FloatField(blank=True, null=True)),
                ('eonet_event_frequency', models.FloatField(default=0, help_text='Average EONET events per month')),
                ('total_historical_events', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('location_name', 'latitude', 'longitude')},
            },
        ),
        migrations.CreateModel(
            name='NASAEONETEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=200)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='open', max_length=50)),
                ('magnitude_value', models.FloatField(blank=True, null=True)),
                ('magnitude_unit', models.CharField(blank=True, max_length=50)),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-event_date'],
                'indexes': [models.Index(fields=['category'], name='disasters_n_categor_d96cad_idx'), models.Index(fields=['latitude', 'longitude'], name='disasters_n_latitud_ffa540_idx'), models.Index(fields=['event_date'], name='disasters_n_event_d_f8298f_idx')],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=300)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('risk_level', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=20)),
                ('risk_probability', models.FloatField(help_text='0.0 to 1.0')),
                ('risk_score', models.FloatField(help_text='Composite risk score')),
                ('contributing_factors', models.JSONField(default=list)),
                ('earthquake_risk', models.FloatField(default=0)),
                ('weather_risk', models.FloatField(default=0)),
                ('eonet_risk', models.FloatField(default=0)),
                ('anomaly_detected', models.BooleanField(default=False)),
                ('anomaly_details', models.TextField(blank=True)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-risk_probability', '-risk_score'],
                'indexes': [models.Index(fields=['risk_level'], name='disasters_r_risk_le_8f985f_idx'), models.Index(fields=['assessed_at'], name='disasters_r_assesse_8590b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(max_length=255, unique=True)),
                ('location_name', models.CharField(max_length=300)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('event_type', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('extreme', 'Extreme'), ('severe', 'Severe'), ('moderate', 'Moderate'), ('minor', 'Minor')], default='moderate', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('pressure', models.FloatField(blank=True, null=True)),
                ('rainfall', models.FloatField(blank=True, help_text='Rainfall in mm', null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['severity'], name='disasters_w_severit_1ff996_idx'), models.Index(fields=['latitude', 'longitude'], name='disasters_w_latitud_55506b_idx'), models.Index(fields=['event_type'], name='disasters_w_event_t_998b4a_idx')],
            },
        ),
    ]
