# Generated by Django 5.2.12 on 2026-03-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatheralert',
            name='severity',
            field=models.CharField(choices=[('extreme', 'Extreme'), ('severe', 'Severe'), ('moderate', 'Moderate'), ('minor', 'Minor'), ('normal', 'Normal')], default='moderate', max_length=20),
        ),
    ]
