# Generated by Django 5.2.12 on 2026-03-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0002_alter_weatheralert_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafetchlog',
            name='source',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='GDACSEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('event_type', models.CharField(choices=[('FL', 'Flood'), ('TC', 'Tropical Cyclone'), ('VO', 'Volcano'), ('DR', 'Drought'), ('WF', 'Wildfire')], max_length=10)),
                ('alert_level', models.CharField(choices=[('Red', 'Red'), ('Orange', 'Orange'), ('Green', 'Green')], default='Green', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('severity', models.FloatField(blank=True, null=True)),
                ('population_affected', models.IntegerField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('description', models.TextField(blank=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-event_date'],
                'indexes': [models.Index(fields=['event_type'], name='disasters_g_event_t_204e72_idx'), models.Index(fields=['alert_level'], name='disasters_g_alert_l_e98d7d_idx'), models.Index(fields=['latitude', 'longitude'], name='disasters_g_latitud_d09ceb_idx'), models.Index(fields=['event_date'], name='disasters_g_event_d_965c14_idx')],
            },
        ),
        migrations.CreateModel(
            name='WildfireEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('brightness', models.FloatField(blank=True, help_text='Brightness temperature (K)', null=True)),
                ('scan', models.FloatField(blank=True, null=True)),
                ('track', models.FloatField(blank=True, null=True)),
                ('acq_date', models.DateField()),
                ('acq_time', models.CharField(blank=True, max_length=10)),
                ('satellite', models.CharField(blank=True, max_length=50)),
                ('instrument', models.CharField(blank=True, max_length=50)),
                ('confidence', models.CharField(blank=True, max_length=20)),
                ('frp', models.FloatField(blank=True, help_text='Fire Radiative Power (MW)', null=True)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('raw_data', models.JSONField(default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-acq_date'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='disasters_w_latitud_43fb4c_idx'), models.Index(fields=['acq_date'], name='disasters_w_acq_dat_238eae_idx'), models.Index(fields=['confidence'], name='disasters_w_confide_ad9b90_idx')],
            },
        ),
    ]
