# Generated by Django 5.2.12 on 2026-03-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0004_remove_eonet_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='N8NAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('earthquake', 'Earthquake'), ('risk', 'Risk Assessment')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('magnitude', models.FloatField(blank=True, null=True)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
