# Generated by Django 5.2.12 on 2026-03-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0005_n8nalertlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='n8nalertlog',
            name='event_ref',
            field=models.CharField(blank=True, help_text='Unique event ID or assessment ID', max_length=255),
        ),
    ]
