# Generated by Django 5.2.12 on 2026-03-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0006_n8nalertlog_event_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disaster_type', models.CharField(choices=[('flood', 'Flood'), ('earthquake', 'Earthquake'), ('fire', 'Fire / Wildfire'), ('cyclone', 'Cyclone / Storm'), ('landslide', 'Landslide'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('description', models.TextField()),
                ('location_name', models.CharField(blank=True, max_length=300)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('people_affected', models.IntegerField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
    ]
