# Generated by Django 5.2.12 on 2026-03-23 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0007_crowd_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrowdReport',
        ),
    ]
